-- Insert sample software data
INSERT INTO "Software" (
  "id", 
  "name", 
  "description", 
  "category", 
  "vendor", 
  "costPerLicense", 
  "billingCycle", 
  "logoUrl", 
  "websiteUrl", 
  "organizationId", 
  "requiresApproval", 
  "autoProvision", 
  "createdAt", 
  "updatedAt"
) VALUES
-- Development Tools
(
  'sw_vscode',
  'Visual Studio Code',
  'Lightweight but powerful source code editor with built-in support for JavaScript, TypeScript and Node.js',
  'Development',
  'Microsoft',
  0,
  'MONTHLY',
  'https://code.visualstudio.com/assets/images/code-stable.png',
  'https://code.visualstudio.com',
  'org_default',
  false,
  true,
  NOW(),
  NOW()
),
(
  'sw_intellij',
  'IntelliJ IDEA Ultimate',
  'Capable and ergonomic Java IDE for enterprise developers',
  'Development',
  'JetBrains',
  149.00,
  'YEARLY',
  'https://resources.jetbrains.com/storage/products/intellij-idea/img/meta/intellij-idea_1280x800.png',
  'https://www.jetbrains.com/idea/',
  'org_default',
  true,
  false,
  NOW(),
  NOW()
),
-- Design Tools
(
  'sw_figma',
  'Figma',
  'Collaborative interface design tool',
  'Design',
  'Figma Inc.',
  12.00,
  'MONTHLY',
  'https://cdn.sanity.io/images/599r6htc/localized/46a76c802176eb17b04e12108de7e7e0f3736dc6-1024x1024.png',
  'https://www.figma.com',
  'org_default',
  true,
  true,
  NOW(),
  NOW()
),
-- Productivity Tools
(
  'sw_slack',
  'Slack',
  'Channel-based messaging platform',
  'Communication',
  'Salesforce',
  8.00,
  'MONTHLY',
  'https://a.slack-edge.com/80588/marketing/img/meta/slack_hash_256.png',
  'https://slack.com',
  'org_default',
  false,
  true,
  NOW(),
  NOW()
),
(
  'sw_notion',
  'Notion',
  'All-in-one workspace for notes, docs, and collaboration',
  'Productivity',
  'Notion Labs Inc.',
  10.00,
  'MONTHLY',
  'https://www.notion.so/cdn-cgi/image/format=auto,width=256,quality=100/front-static/shared/icons/notion-app-icon-3d.png',
  'https://www.notion.so',
  'org_default',
  true,
  false,
  NOW(),
  NOW()
),
-- Security Tools
(
  'sw_1password',
  '1Password',
  'Password manager that keeps all passwords secure behind one',
  'Security',
  '1Password',
  7.99,
  'MONTHLY',
  'https://1password.com/img/logo-v1.svg',
  'https://1password.com',
  'org_default',
  false,
  true,
  NOW(),
  NOW()
),
-- Cloud Services
(
  'sw_aws',
  'AWS Developer Access',
  'Access to AWS services for development and testing',
  'Cloud',
  'Amazon Web Services',
  NULL,
  'MONTHLY',
  'https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png',
  'https://aws.amazon.com',
  'org_default',
  true,
  false,
  NOW(),
  NOW()
),
-- Analytics
(
  'sw_mixpanel',
  'Mixpanel',
  'Product analytics for mobile and web',
  'Analytics',
  'Mixpanel Inc.',
  25.00,
  'MONTHLY',
  'https://mixpanel.com/tailwind-images/logo-small-square.svg',
  'https://mixpanel.com',
  'org_default',
  true,
  false,
  NOW(),
  NOW()
); 